### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ryrych** [leanpub/translations#33]
*Edit* button on book hover is not a part of translations. 

![screen shot 2018-08-30 at 21 29 41](https://user-images.githubusercontent.com/278637/44874572-e19ef700-ac9b-11e8-81bc-5510f8447e59.png)

*Pages* should have plural form. For Polish.

![screen shot 2018-08-30 at 21 30 54](https://user-images.githubusercontent.com/278637/44874703-570ac780-ac9c-11e8-9878-d2d0b8ee53ad.png)

- 1 strona
- 2 strony
- 5 stron

Similar traslations:

```yaml
  w_book_freshness_timestamp:
    lt_1_minute: "Just now!"
    lt_2_minutes: "A minute ago"
    lt_45_minutes: "%{minutes} minutes ago"
    lt_90_minutes: "~1 hour ago"
    lt_24_hours: "%{hours} hours ago"
    lt_48_hours: "Yesterday"
    lt_30_days: "%{days} days ago"
    lt_60_days: "Last month"
    lt_1_year: "%{months} months ago"
```

## [Email author page](https://leanpub.com/dom-wytwarzania-slownik/email_author/new)

- "Email the Author"
- "You can use this page to email %{author} about %{title}."
- "YOUR EMAIL ADDRESS"
- "Please include an email address so the author can respond to your query"
- "This message will be sent to %{author}"
- "Email %{author}"

![screen shot 2018-08-30 at 21 55 19](https://user-images.githubusercontent.com/278637/44876106-5ecc6b00-aca0-11e8-90cc-57f2f32245c6.png)
